<?php

namespace App\Constants;

return [

    'OUR_SOLUTION_MAX_IMAGE_SIZE'=>'3000',
    'OUR_SOLUTION_MAX_IMAGE_MIN_SIZE'=>'5',
    //Home
    'SLIDER_IMAGE_MAX_SIZE'=>'2048',
    'SLIDER_IMAGE_MIN_SIZE'=>'600',

    'COURSES_OFFERED_IMAGE_MAX_SIZE'=>'3000',
    'COURSES_OFFERED_IMAGE_MIN_SIZE'=>'5',

    'TESTIMONIAL_IMAGE_MAX_SIZE'=>'5000',
    'TESTIMONIAL_IMAGE_MIN_SIZE'=>'10',

    'GALLERY_IMAGE_MAX_SIZE'=>'10240',
    'GALLERY_IMAGE_MIN_SIZE'=>'50',

    'OUR_RESULT_IMAGE_MAX_SIZE'=>'10240',
    'OUR_RESULT_IMAGE_MIN_SIZE'=>'10',
];